<section class="x-arrow-with-saquo">
  <h3 class="title">Arrow with saquo example</h3>

  {% set direction = "right" %}
  {% include '../arrow-with-saquo.html.swig' %}

  {% set direction = "left" %}
  {% include '../arrow-with-saquo.html.swig' %}

  {% set direction = "top" %}
  {% include '../arrow-with-saquo.html.swig' %}

  {% set direction = "bottom" %}
  {% include '../arrow-with-saquo.html.swig' %}
</section>
