<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "WebSite",
  "url": "{{ site.url }}",
  "name": "{{ site.title }}",
  "author": {
    "@type": "Person",
    "name": "Csongor Bartus"
  },
  "description": "{{ site.description }}",
  "publisher": {
    "@type": "Organization",
    "name": "Metamn",
    "logo": {
      "@type": "ImageObject",
      "url": "http://metamn.io/assets/images/icons/favicon-196x196.png"
    }
  }
}
</script>
